spring:  
  datasource:
    url: "jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
        path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true

jwt:
  issuer: "blacknode-backend"
  expiration: 600000
  development-auto-generate: true
  
logging:
  level:
    org.hibernate: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.converter: TRACE
    org.hibernate.metamodel.model.convert: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: TRACE
    root: DEBUG
