server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      base-path: /actuator

jwt:
  issuer: "blacknode-backend-dev"
  audience: "api"
  expiration: 900000
  secret: "f0KeSbOwDytCaVKhPKqaBOkFM7t80hMc6mGVIArVJdI="
  
logging:
  level:
    org.hibernate: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.converter: TRACE
    org.hibernate.metamodel.model.convert: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: TRACE