spring:
  datasource:
    url: "${DB_URL:}"
    username: "${DB_USERNAME:}"
    password: "${DB_PASSWORD:}"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  issuer: "blacknode-backend-test"
  expiration: 600000
  secret: "${JWT_SECRET:}"
	
logging:
  level:
    org.hibernate: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.converter: TRACE
    org.hibernate.metamodel.model.convert: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: TRACE
    root: DEBUG
		
